# ---------------------------------------------------- #
# Note: this file originates in template-action-node #
# ---------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

permissions:
  contents: read

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/push-action-node.yml@9b5f988ef8240b3d39d7c3c4ef4c1b558d9a1070 # master
    secrets: inherit
    permissions:
      contents: write
      statuses: write
      packages: write
      pull-requests: write
